seed: 0
device: cuda:0
n_thread: 1
base_dir: ""
offline: False
pretrain_path: ""
tag: default
env_type: mujoco
dim_c: [2, 2]
n_traj: 1
supervision: 0.0

gamma: 0.99
mini_batch_size: 256
n_sample: 50000 # replay buffer size
init_sample: 1000 # only for streaming style training
update_interval: 10 # only for streaming style training
max_explore_step: 5e6 # in offline setting, this will be max update
use_auxiliary_obs: False

num_eval_episodes: 20
log_interval: 1000
eval_interval: 10000

defaults:
  - _self_
  - alg: mahil
  - env: LaborDivision2
  - optional base: "" # just to save a special_setting name to enable OmegaConf interpolation
  - optional special_setting: ${alg}/${base} # actual yaml path for a special setting
